### ISSUE TITLE
12864 display reset button wrong bottom height

### ISSUE THREAD

**Issue by MaKaNu** [SecKit/SK-Go_SK-Mini#1]
My printed Reset Button from [https://github.com/SecKit/SK-Go_SK-Mini/blob/master/printed%20parts%20STL/2.%20Recommended/6.%2012864%20Display%20cover/12864%20display%20reset%20button.stl](url) has the wrong height to reach the display reset button in short distance. This left the button unstable. I measured the distance between reset button and display cover with ~5 mm if the bottom of the button in not about 2 mm rather around 4 to 4.5 mm it would be more stable.

**Comment by MaKaNu** [comment]
I created two Versions that should work better: a short button and a long button

**Comment by SecKit** [comment]
Hi @MaKaNu, thank you for reporting this issue. I just updated a new version of cover and button (3b5fd47) with these improvements:

- bolt hole alignment
- shorter and longer reset button
- add support between cover and PCB to prevent pressing cover and erroneously trigger reset button

**Comment by MaKaNu** [comment]
Looking Great. I close the Issue.
